# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.16, name: tag0},
    {id: 1, size: 0.16, name: tag1},
    {id: 2, size: 0.16, name: tag2},
    {id: 3, size: 0.16, name: tag3},
    {id: 4, size: 0.16, name: tag4},
    {id: 5, size: 0.16, name: tag5},
    {id: 6, size: 0.16, name: tag6},
    {id: 7, size: 0.16, name: tag7},
    {id: 8, size: 0.16, name: tag8},
    {id: 9, size: 0.16, name: tag9},
    {id: 10, size: 0.16, name: tag10},
    {id: 11, size: 0.16, name: tag11},
    {id: 12, size: 0.16, name: tag12},
    {id: 13, size: 0.16, name: tag13},
    {id: 14, size: 0.16, name: tag14},
    {id: 15, size: 0.16, name: tag15},
    {id: 16, size: 0.16, name: tag16},
    {id: 17, size: 0.16, name: tag17},
    {id: 18, size: 0.16, name: tag18},
    {id: 19, size: 0.16, name: tag19},
    {id: 20, size: 0.16, name: tag20},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
